version: "3"
services:
  web:
    image: nginx
    depends_on:
      - app
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ${PROJECT_PATH}:/work
      - ./dockerbuild/nginx/logs:/var/log/nginx
      - ./dockerbuild/nginx/default.conf:/etc/nginx/conf.d/default.conf

  app:
    build:
      context: ./dockerbuild/php
    ports:
      - ${LARAVEL_SERVER_PORT}:8000
    volumes:
      - ${PROJECT_PATH}:/work
    working_dir: /work

  db:
    build:
      context: ./dockerbuild/db
    volumes:
      - practice-ga-data:/var/lib/mysql
      - ./dockerbuild/db/logs:/var/log/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=Asia/Tokyo
    ports:
      - ${MYSQL_PORT}:3306

volumes:
  practice-ga-data:
    driver: local
