name: Tests
# 複数指定もできる on: [push , pull_request]
on: push

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: ga_test
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    container:
        image: php:7.4-fpm
        env:
          DB_CONNECTION: ga_testing

    steps:
      - uses: actions/checkout@v2.0.0

      - name: Update apt-get
        run: sudo apt-get update

      - name: Docker php extensions install
        run: sudo docker-php-ext-install pdo_mysql

      - name: Install composer
        run: cd /usr/bin && curl -s http://getcomposer.org/installer | php && ln -s /usr/bin/composer.phar /usr/bin/composer

      - name: Cache composer dependencies
        uses: actions/cache@v1.1.0
        with:
          path: vendor
          key: composer-${{ hashFiles('src/composer.lock') }}

      - name: Run composer install
        run: composer install -n --prefer-dist
        env:
          APP_ENV: testing
        working-directory: src

      - name: Prepare Laravel Application
        run: |
          cp .env.example .env
          php artisan key:generate
        working-directory: src

      - name: Run tests
        run: ./vendor/bin/phpunit
        # env:
        #   DB_CONNECTION: ga_testing
        working-directory: src

      - name: Upload artifacts
        uses: actions/upload-artifact@master
        if: failure()
        with:
          name: Logs
          path: ./src/storage/logs
